// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PaymentSettings payment settings
//
// swagger:model paymentSettings
type PaymentSettings struct {

	// default invoice expiration in minutes
	// Required: true
	// Minimum: 1
	// Maximum: 1440
	DefaultExpirationMinutes int64 `json:"defaultExpirationMinutes"`
}

// Validate validates this payment settings
func (m *PaymentSettings) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDefaultExpirationMinutes(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PaymentSettings) validateDefaultExpirationMinutes(formats strfmt.Registry) error {
	if err := validate.Required("defaultExpirationMinutes", "body", int64(m.DefaultExpirationMinutes)); err != nil {
		return err
	}

	if err := validate.Minimum(
		"defaultExpirationMinutes",
		"body",
		float64(m.DefaultExpirationMinutes),
		1,
		false,
	); err != nil {
		return err
	}

	if err := validate.Maximum(
		"defaultExpirationMinutes",
		"body",
		float64(m.DefaultExpirationMinutes),
		1440,
		false,
	); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this payment settings based on context it is used
func (m *PaymentSettings) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PaymentSettings) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PaymentSettings) UnmarshalBinary(b []byte) error {
	var res PaymentSettings
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
