// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/oxygenpay/oxygen/pkg/api-kms/v1/model"
)

// NewCreateBitcoinTransactionParams creates a new CreateBitcoinTransactionParams object,
// with the default timeout for this client.
func NewCreateBitcoinTransactionParams() *CreateBitcoinTransactionParams {
	return &CreateBitcoinTransactionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewCreateBitcoinTransactionParamsWithTimeout creates a new CreateBitcoinTransactionParams object
// with the ability to set a timeout on a request.
func NewCreateBitcoinTransactionParamsWithTimeout(timeout time.Duration) *CreateBitcoinTransactionParams {
	return &CreateBitcoinTransactionParams{
		timeout: timeout,
	}
}

// NewCreateBitcoinTransactionParamsWithContext creates a new CreateBitcoinTransactionParams object
// with the ability to set a context for a request.
func NewCreateBitcoinTransactionParamsWithContext(ctx context.Context) *CreateBitcoinTransactionParams {
	return &CreateBitcoinTransactionParams{
		Context: ctx,
	}
}

// NewCreateBitcoinTransactionParamsWithHTTPClient creates a new CreateBitcoinTransactionParams object
// with the ability to set a custom HTTPClient for a request.
func NewCreateBitcoinTransactionParamsWithHTTPClient(client *http.Client) *CreateBitcoinTransactionParams {
	return &CreateBitcoinTransactionParams{
		HTTPClient: client,
	}
}

/*
CreateBitcoinTransactionParams contains all the parameters to send to the API endpoint

	for the create bitcoin transaction operation.

	Typically these are written to a http.Request.
*/
type CreateBitcoinTransactionParams struct {

	// Data.
	Data *model.CreateBitcoinTransactionRequest

	/* WalletID.

	   Wallet UUID
	*/
	WalletID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the create bitcoin transaction params (not the query body).
func (o *CreateBitcoinTransactionParams) WithDefaults() *CreateBitcoinTransactionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the create bitcoin transaction params (not the query body).
func (o *CreateBitcoinTransactionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the create bitcoin transaction params
func (o *CreateBitcoinTransactionParams) WithTimeout(timeout time.Duration) *CreateBitcoinTransactionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create bitcoin transaction params
func (o *CreateBitcoinTransactionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create bitcoin transaction params
func (o *CreateBitcoinTransactionParams) WithContext(ctx context.Context) *CreateBitcoinTransactionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create bitcoin transaction params
func (o *CreateBitcoinTransactionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create bitcoin transaction params
func (o *CreateBitcoinTransactionParams) WithHTTPClient(client *http.Client) *CreateBitcoinTransactionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create bitcoin transaction params
func (o *CreateBitcoinTransactionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the create bitcoin transaction params
func (o *CreateBitcoinTransactionParams) WithData(data *model.CreateBitcoinTransactionRequest) *CreateBitcoinTransactionParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the create bitcoin transaction params
func (o *CreateBitcoinTransactionParams) SetData(data *model.CreateBitcoinTransactionRequest) {
	o.Data = data
}

// WithWalletID adds the walletID to the create bitcoin transaction params
func (o *CreateBitcoinTransactionParams) WithWalletID(walletID string) *CreateBitcoinTransactionParams {
	o.SetWalletID(walletID)
	return o
}

// SetWalletID adds the walletId to the create bitcoin transaction params
func (o *CreateBitcoinTransactionParams) SetWalletID(walletID string) {
	o.WalletID = walletID
}

// WriteToRequest writes these params to a swagger request
func (o *CreateBitcoinTransactionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param walletId
	if err := r.SetPathParam("walletId", o.WalletID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
