// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/oxygenpay/oxygen/pkg/api-kms/v1/model"
)

// CreateBitcoinTransactionReader is a Reader for the CreateBitcoinTransaction structure.
type CreateBitcoinTransactionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateBitcoinTransactionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateBitcoinTransactionCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateBitcoinTransactionBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateBitcoinTransactionCreated creates a CreateBitcoinTransactionCreated with default headers values
func NewCreateBitcoinTransactionCreated() *CreateBitcoinTransactionCreated {
	return &CreateBitcoinTransactionCreated{}
}

/*
	CreateBitcoinTransactionCreated describes a response with status code 201, with default header values.

Transaction Created
*/
type CreateBitcoinTransactionCreated struct {
	Payload *model.BitcoinTransaction
}

func (o *CreateBitcoinTransactionCreated) Error() string {
	return fmt.Sprintf("[POST /wallet/{walletId}/transaction/btc][%d] createBitcoinTransactionCreated  %+v", 201, o.Payload)
}
func (o *CreateBitcoinTransactionCreated) GetPayload() *model.BitcoinTransaction {
	return o.Payload
}

func (o *CreateBitcoinTransactionCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.BitcoinTransaction)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateBitcoinTransactionBadRequest creates a CreateBitcoinTransactionBadRequest with default headers values
func NewCreateBitcoinTransactionBadRequest() *CreateBitcoinTransactionBadRequest {
	return &CreateBitcoinTransactionBadRequest{}
}

/*
	CreateBitcoinTransactionBadRequest describes a response with status code 400, with default header values.

Validation error / Not found
*/
type CreateBitcoinTransactionBadRequest struct {
	Payload *model.ErrorResponse
}

func (o *CreateBitcoinTransactionBadRequest) Error() string {
	return fmt.Sprintf("[POST /wallet/{walletId}/transaction/btc][%d] createBitcoinTransactionBadRequest  %+v", 400, o.Payload)
}
func (o *CreateBitcoinTransactionBadRequest) GetPayload() *model.ErrorResponse {
	return o.Payload
}

func (o *CreateBitcoinTransactionBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(model.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
