// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// BitcoinTransaction bitcoin transaction
//
// swagger:model bitcoinTransaction
type BitcoinTransaction struct {
	// raw transaction
	RawTransaction string `json:"rawTransaction"`
}

// Validate validates this bitcoin transaction
func (m *BitcoinTransaction) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this bitcoin transaction based on context it is used
func (m *BitcoinTransaction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BitcoinTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BitcoinTransaction) UnmarshalBinary(b []byte) error {
	var res BitcoinTransaction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
