// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BitcoinUTXO bitcoin u t x o
//
// swagger:model bitcoinUTXO
type BitcoinUTXO struct {
	// address
	Address string `json:"address,omitempty"`

	// amount sats
	// Required: true
	// Minimum: 1
	AmountSats int64 `json:"amountSats"`

	// hash
	// Required: true
	Hash string `json:"hash"`

	// index
	// Required: true
	// Minimum: 0
	Index int64 `json:"index"`

	// script
	Script string `json:"script,omitempty"`
}

// Validate validates this bitcoin u t x o
func (m *BitcoinUTXO) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.MinimumInt("amountSats", "body", m.AmountSats, 1, false); err != nil {
		res = append(res, err)
	}

	if err := validate.RequiredString("hash", "body", m.Hash); err != nil {
		res = append(res, err)
	}

	if err := validate.MinimumInt("index", "body", m.Index, 0, false); err != nil {
		res = append(res, err)
	}

	if err := validate.MaximumInt("index", "body", m.Index, 4294967295, false); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this bitcoin u t x o based on context it is used
func (m *BitcoinUTXO) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BitcoinUTXO) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BitcoinUTXO) UnmarshalBinary(b []byte) error {
	var res BitcoinUTXO
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
