// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// BitcoinOutput bitcoin output
//
// swagger:model bitcoinOutput
type BitcoinOutput struct {
	// address
	// Required: true
	Address string `json:"address"`

	// amount sats
	// Required: true
	// Minimum: 1
	AmountSats int64 `json:"amountSats"`
}

// Validate validates this bitcoin output
func (m *BitcoinOutput) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.RequiredString("address", "body", m.Address); err != nil {
		res = append(res, err)
	}

	if err := validate.MinimumInt("amountSats", "body", m.AmountSats, 1, false); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this bitcoin output based on context it is used
func (m *BitcoinOutput) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *BitcoinOutput) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *BitcoinOutput) UnmarshalBinary(b []byte) error {
	var res BitcoinOutput
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
