// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CreateBitcoinTransactionRequest create bitcoin transaction request
//
// swagger:model createBitcoinTransactionRequest
type CreateBitcoinTransactionRequest struct {
	// fee sat per v byte
	FeeSatPerVByte int64 `json:"feeSatPerVByte,omitempty"`

	// inputs
	// Required: true
	Inputs []*BitcoinUTXO `json:"inputs"`

	// is test
	IsTest bool `json:"isTest"`

	// outputs
	// Required: true
	Outputs []*BitcoinOutput `json:"outputs"`

	// rbf
	RBF bool `json:"rbf"`
}

// Validate validates this create bitcoin transaction request
func (m *CreateBitcoinTransactionRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.Required("inputs", "body", m.Inputs); err != nil {
		res = append(res, err)
	} else if len(m.Inputs) == 0 {
		res = append(res, errors.Required("inputs", "body", m.Inputs))
	}

	for i := range m.Inputs {
		if m.Inputs[i] == nil {
			res = append(res, errors.Required("inputs", "body", m.Inputs[i]))
			continue
		}
		if err := m.Inputs[i].Validate(formats); err != nil {
			res = append(res, err)
		}
	}

	if err := validate.Required("outputs", "body", m.Outputs); err != nil {
		res = append(res, err)
	} else if len(m.Outputs) == 0 {
		res = append(res, errors.Required("outputs", "body", m.Outputs))
	}

	for i := range m.Outputs {
		if m.Outputs[i] == nil {
			res = append(res, errors.Required("outputs", "body", m.Outputs[i]))
			continue
		}
		if err := m.Outputs[i].Validate(formats); err != nil {
			res = append(res, err)
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this create bitcoin transaction request based on context it is used
func (m *CreateBitcoinTransactionRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CreateBitcoinTransactionRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreateBitcoinTransactionRequest) UnmarshalBinary(b []byte) error {
	var res CreateBitcoinTransactionRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
