logger:
  pretty: true
  level: info

oxygen:
  postgres:
    data_source: "host=localhost sslmode=disable dbname=oxygen user=oxygen password=qwerty pool_max_conns=32"
  server:
    port: 80
    session:
      path: /opt/oxygen/sessions/
      secret: session-secret
    cors:
      allow_origins:
        - https://pay.site.com
  processing:
    webhook_base_path: https://pay.site.com
    payment_frontend_base_path: https://pay.site.com
  auth:
    email:
      user_email: your.address@gmail.com
      user_password: your-password-at-least-8-chars

kms:
  server:
    port: 14000
  store:
    path: /opt/oxygen/kms.db

providers:
  chain:
    bitcoin_mainnet_explorer_url: https://blockstream.info/api
    bitcoin_mainnet_explorer_fallback_urls:
      - https://mempool.space/api
    bitcoin_testnet_explorer_url: https://blockstream.info/testnet/api
    bitcoin_testnet_explorer_fallback_urls:
      - https://mempool.space/testnet/api
    litecoin_mainnet_explorer_url: https://litecoinspace.org/api
    litecoin_mainnet_explorer_fallback_urls:
    litecoin_testnet_explorer_url: https://litecoinspace.org/testnet/api
    litecoin_testnet_explorer_fallback_urls:
    ethereum_mainnet_rpc_url:
    ethereum_testnet_rpc_url:
    matic_mainnet_rpc_url:
    matic_testnet_rpc_url:
    bsc_mainnet_rpc_url:
    bsc_testnet_rpc_url:
    evm_scan_blocks: 1200
  tatum:
    api_key:
    test_api_key:
    tatum_hmac_secret:
  trongrid:
    api_key:
  kms:
    host: localhost:14000
