// Code generated by go-swagger; DO NOT EDIT.

package model

import "github.com/go-openapi/swag"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// CreatePaymentFromLinkRequest create payment from link request
//
// swagger:model createPaymentFromLinkRequest
type CreatePaymentFromLinkRequest struct {

	// Donation amount in the link fiat currency.
	// Example: 25
	Price float64 `json:"price"`
}

// MarshalBinary interface implementation
func (m *CreatePaymentFromLinkRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CreatePaymentFromLinkRequest) UnmarshalBinary(b []byte) error {
	var res CreatePaymentFromLinkRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
