// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ObservedPaymentTransaction Transaction currently observed on-chain or in mempool without mutating payment state
//
// swagger:model observedPaymentTransaction
type ObservedPaymentTransaction struct {

	// Observed incoming amount in raw units
	// Example: 3076
	// Required: true
	Amount string `json:"amount"`

	// Human readable observed amount
	// Example: 0.00003076
	// Required: true
	AmountFormatted string `json:"amountFormatted"`

	// Current confirmation count
	// Example: 0
	// Required: true
	Confirmations int64 `json:"confirmations"`

	// Blockchain explorer link
	// Example: https://blockstream.info/tx/73dfbf0b657e0a76d439c5cc9a92038c77adbef950a5ae634cc44a958a4b65c3
	ExplorerLink string `json:"explorerLink,omitempty"`

	// Whether this transaction has reached required confirmations
	// Example: false
	// Required: true
	IsConfirmed bool `json:"isConfirmed"`

	// Whether this transaction is known only from the mempool
	// Example: true
	// Required: true
	IsMempool bool `json:"isMempool"`

	// Confirmations required before payment state is updated
	// Example: 6
	// Required: true
	RequiredConfirmations int64 `json:"requiredConfirmations"`

	// Sender address when available from the explorer/RPC response
	// Example: bc1q9pnvzdakvsag0g92kqw4m4ukvpv753ssed6ue5
	SenderAddress string `json:"senderAddress,omitempty"`

	// Blockchain transaction hash
	// Example: 73dfbf0b657e0a76d439c5cc9a92038c77adbef950a5ae634cc44a958a4b65c3
	// Required: true
	TransactionHash string `json:"transactionHash"`
}

// Validate validates this observed payment transaction
func (m *ObservedPaymentTransaction) Validate(formats strfmt.Registry) error {
	var res []error

	if err := validate.RequiredString("amount", "body", m.Amount); err != nil {
		res = append(res, err)
	}

	if err := validate.RequiredString("amountFormatted", "body", m.AmountFormatted); err != nil {
		res = append(res, err)
	}

	if err := validate.RequiredString("transactionHash", "body", m.TransactionHash); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// ContextValidate validates this observed payment transaction based on context it is used
func (m *ObservedPaymentTransaction) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ObservedPaymentTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ObservedPaymentTransaction) UnmarshalBinary(b []byte) error {
	var res ObservedPaymentTransaction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
