// Code generated by go-swagger; DO NOT EDIT.

package model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SupportedPaymentMethod PaymentType
//
// swagger:model supportedPaymentMethod
type SupportedPaymentMethod struct {

	// blockchain
	Blockchain string `json:"blockchain"`

	// blockchain name
	BlockchainName string `json:"blockchainName"`

	// Currency type, either native coin or token
	// Enum: [coin token]
	// Example: token
	CurrencyType string `json:"currencyType"`

	// display name
	DisplayName string `json:"displayName"`

	// is test
	IsTest bool `json:"isTest"`

	// name
	Name string `json:"name"`

	// network Id
	NetworkID string `json:"networkId"`

	// ticker
	Ticker string `json:"ticker"`

	// Token contract address for token payment methods
	// Example: 0xdac17f958d2ee523a2206206994597c13d831ec7
	TokenContractAddress string `json:"tokenContractAddress"`
}

// Validate validates this supported payment method
func (m *SupportedPaymentMethod) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this supported payment method based on context it is used
func (m *SupportedPaymentMethod) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SupportedPaymentMethod) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SupportedPaymentMethod) UnmarshalBinary(b []byte) error {
	var res SupportedPaymentMethod
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
