server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    include /etc/nginx/mime.types;
    types {
        text/yaml yml yaml;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /specs/ {
        try_files $uri $uri/index.html =404;
    }
}
